# Generated by Django 3.0.6 on 2020-06-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
